// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxTrophy,
    vaxBoolIcon
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin
} from "@/utils/mixins.js";

import {
    unitTypesPluralStr,
} from "@/utils/i18n-data.js";

import {
    toPercentString,
} from "@/utils/misc.js"

export default {
  name: "rmStatsUnits",
  components: {
    vaxView,
    vaxTrophy,
    vaxBoolIcon
  },
  methods: {
    toPercentString: toPercentString,
  },
  data: () => ( {
    unitTypesPlural: unitTypesPluralStr,
  } ),
  mixins: [
    jsonViewDataMixin
  ]
}
