// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxBox,
    vaxButton
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin
  } from "../../utils/mixins.js";

export default {
  name: "rmJournalView",
  components: {
    vaxView,
    vaxBox,
    vaxButton
  },
  methods: {
    journalEdit ( editable, i ) {
      if ( editable ) {
        this.$router.push( { path: "/journalEdit", query: { dayNr: i } } );
      }
    }
  },
  mixins: [
    jsonViewDataMixin
  ]
}
