// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxForm,
    vaxCombobox,
    vaxFileSelect,
    vaxField,
    vaxFieldset,
    vaxCheckbox,
    vaxButton,
    vaxInputField,
    vaxMailingBox,
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin,
    jsonDataMixin,
    submitPostMixin,
} from "@/utils/mixins.js";

/*
import {
    mailerTypesStr,
} from "@/utils/i18n-data.js";
*/

const DATA_FILE_LIST = "fileList";

export default {
  name: "rmMailing",
  components: {
    vaxView,
    vaxForm,
    vaxCombobox,
    vaxFileSelect,
    vaxField,
    vaxInputField,
    vaxMailingBox,
  },
  data: () => ( {
//    mailerTypes: mailerTypesStr,
  } ),
  methods: {
    mailTo ( event ) {
      this.submitPost( event );
      /*
      const newHref = 'mailto:example@example.com,example2@example2.com?subject=test&body=treść';
      window.open( newHref );
      */
    },
    goToFiles () {
      this.$router.push( "/files" );
    },
  },
  mixins: [
    jsonViewDataMixin,
    jsonDataMixin( DATA_FILE_LIST ),    
    submitPostMixin,
  ]
}
