// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxForm,
    vaxFieldset,
    vaxInputField,
    rmFormUnit,
} from "@/components";
// *** AUTOGENERATED end

import {
  submitPostMixin,
  jsonViewDataMixin,
} from "@/utils/mixins.js";

export default {
  name: "rmManageUnit",
  components: {
    vaxView,
    vaxForm,
    vaxFieldset,
    vaxInputField,
    rmFormUnit,
  },
  data () {
    return {
      afterPost: () => this.getJsonViewData(),
    };
  },
  mixins: [
    submitPostMixin,
    jsonViewDataMixin,  
  ]
}
