// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxTrophy,
    vaxBoolIcon
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin,
} from "@/utils/mixins.js";

import {
    toPercentString,
} from "@/utils/misc.js"

export default {
  name: "rmStatsCities",
  components: {
    vaxView,
    vaxTrophy,
    vaxBoolIcon
  },
  methods: {
    toPercentString: toPercentString,
  },
  mixins: [
    jsonViewDataMixin,
  ],
}
