// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxTrophy,
    vaxBoolIcon
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin,
    submitPostMixin,
} from "@/utils/mixins.js";

import {
    toPercentString,
} from "@/utils/misc.js"

export default {
  name: "rmStatsClazzes",
  components: {
    vaxView,
    vaxTrophy,
    vaxBoolIcon
  },
  data () {
    return {
      afterPost: (fd) => {
        this.$router.push( "journalView" );
      },
    }
  },
  methods: {
    toPercentString: toPercentString,
  },
  mixins: [
    jsonViewDataMixin,
    submitPostMixin,
  ]
}
