// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin
} from "@/utils/mixins.js";
  
import {
    unitTypesPluralStr,
    printMaterialTypesStr,
} from "@/utils/i18n-data.js";

export default {
  name: "rmReqPrints",
  components: {
    vaxView,
  },
  data: () => ( {
    unitTypesPlural: unitTypesPluralStr,
    printMaterialTypes: printMaterialTypesStr,
  } ),
  mixins: [
    jsonViewDataMixin,
  ],
}
