// *** AUTOGENERATED // placing any import before this line will break autogeneration
// *** AUTOGENERATED end

export default {
  name: "appHome",
  data () {
    return this.$store.state.pkg;
  }
}

