// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    rmFormCampaign,
} from "@/components";
// *** AUTOGENERATED end

import {
  submitPostMixin,
  jsonViewDataMixin,
} from "@/utils/mixins.js";

export default {
  name: "rmAddCampaign",
  components: {
    vaxView,
    rmFormCampaign,
  },
  mixins: [
    submitPostMixin,
    jsonViewDataMixin,
  ],
}
