// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    rmFormCity,
} from "@/components";
// *** AUTOGENERATED end

import {
  submitPostMixin,
  jsonViewDataMixin
} from "@/utils/mixins.js";

export default {
  name: "rmAddCity",
  components: {
    vaxView,
    rmFormCity,
  },
  mixins: [
    submitPostMixin,
    jsonViewDataMixin
  ]
}
