// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxTrophy
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin
} from "@/utils/mixins.js";

import {
    ageOptionsStr,
} from "@/utils/i18n-data.js";

export default {
  name: "rmReqRewardsUnit",
  components: {
    vaxView,
    vaxTrophy
  },
  methods: {
    getAgeOptionName: ( item ) => ageOptionsStr[item + 1 ?? 0],
  },
  mixins: [
    jsonViewDataMixin
  ]
}
