// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
} from "@/components";
// *** AUTOGENERATED end

export default {
  name: "rmReports",
  components: {
    vaxView,
  },
  data: () => ( {
  } ),
  beforeCreate () {
//    window.location = "/reports";
  },
  mounted () {
//    window.location.hash = "#/message";
  }
}
