// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    datePicker,

    vaxView,
    vaxForm,
    vaxButton,
    vaxInputField,
    rmAgeCategorySelect
} from "@/components";
// *** AUTOGENERATED end

import "flatpickr/dist/flatpickr.css";
import {Polish} from "@/utils/flatpickr-l10n-pl.mjs";

import {
    jsonViewDataMixin,
    submitPostMixin,
} from "@/utils/mixins.js";

import {
    ageOptionsStr
} from "@/utils/i18n-data.js";

export default {
    name: "rmRewardsGroup",
    components: {
        datePicker,

        vaxView,
        vaxForm,
        vaxButton,
        vaxInputField,
        rmAgeCategorySelect
    },
    data() {

        return {
            datePickerConfig1: {
                locale: Polish,
                dateFormat:
                    "d-m-Y",
                allowInput: true,
            },
            afterPost: () => this.getJsonViewData(),
//      removeCaption: "\uF014\u00A0\u00A0" + "Usuń",
        }
    },
    methods: {
        getAgeOptionName: ( item ) => ageOptionsStr[item + 1 ?? 0],
        editGroupReward( event ) {
            const but = event.target;
            var pel;
            for ( pel = but; pel.tagName.toUpperCase() !== "TR"; pel = pel.parentElement ) {
            }
            const inputs = pel.getElementsByTagName( "input" );
            this.submitPostDirect( {
                formName: "editGroupReward", id: inputs[0].value,
                totalCount: inputs[1].value
            } );
        },
    },
    mixins: [
        jsonViewDataMixin,
        submitPostMixin,
    ]
}
