// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxButton,
    vaxCombobox,
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin,
    submitPostMixin,
} from "@/utils/mixins.js";

import {
    toPercentString,
} from "@/utils/misc.js"

export default {
  name: "rmRewardsGroupAssign",
  components: {
    vaxView,
    vaxButton,
    vaxCombobox,
  },
  data () {
    return {
      afterPost: () => this.getJsonViewData(),
    };
  },
  methods: {
    toPercentString: toPercentString,
    assignReward ( event ) {
      const but = event.target;
      var pel;
      for( pel = but; pel.tagName.toUpperCase() !== "TR"; pel = pel.parentElement ) { }
      const selv = pel.getElementsByTagName( "select" )[0].value;
      if ( selv !== -1  ) {
        this.submitPostDirect( { formName: "assignGroupReward", rewardId: selv,
          clazzId: pel.getElementsByTagName( "input" )[0].value } );      
      }
    }
  },
  mixins: [
    jsonViewDataMixin,
    submitPostMixin,
  ]
}
