// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxBox,
    vaxForm,
    vaxButton,
    rmFormCampaign,
} from "@/components";
// *** AUTOGENERATED end

import {
  submitPostMixin,
  jsonViewDataMixin
} from "@/utils/mixins.js";

import {
  windowReload,
} from "@/utils/misc.js";

import {
  campaignStagesStr,
  processFinishedCampaignStr,
} from "@/utils/i18n-data.js";

export default {
  name: "rmManageCampaign",
  components: {
    vaxView,
    vaxBox,
    vaxForm,
    vaxButton,
    rmFormCampaign,
  },
  data () {
    return {
//      afterPost: () => this.getJsonViewData(),
      afterPost: () => windowReload(),
    };
  },
  computed: {
    campaignStage () {
      return campaignStagesStr[this.jsonView?.stage];
    }
  },
  methods: {
    confirmProcessFinishedCampaign () {
      if ( confirm( processFinishedCampaignStr ) ) {
        this.submitPostDirectAndScroll( { formName: 'processFinishedCampaign' } );
      }
    }
  },
  mixins: [
    submitPostMixin,
    jsonViewDataMixin,  
  ]
}
