// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    vaxBox
} from "@/components";
// *** AUTOGENERATED end

import {
    jsonViewDataMixin,
    submitPostMixin,
} from "@/utils/mixins.js";

import {
    unitTypesPluralStr,
} from "@/utils/i18n-data.js";

import {
    windowReload,
} from "@/utils/misc.js";

export default {
  name: "rmRequests",
  components: {
    vaxView,
    vaxBox
  },
  data () {
    return {
      unitTypesPlural: unitTypesPluralStr,
      afterPost: () => this.getJsonViewData(),
    };
  },
  methods: {
    manageUnit ( unit_id ) {
      this.afterPost = ( () => this.$router.push( "/manageUnit", () => windowReload() ) );
      this.submitPostDirect( { formName: "changeUnitContext", id: unit_id } );
    }
  },
  mixins: [
    jsonViewDataMixin,
    submitPostMixin,
  ]
}
