// *** AUTOGENERATED // placing any import before this line will break autogeneration
import {
    vaxView,
    rmFormUnit,
} from "@/components";
// *** AUTOGENERATED end

import {
  submitPostMixin,
  jsonViewDataMixin
} from "@/utils/mixins.js";

import store from "@/store";

export default {
  name: "rmAddUnit",
  components: {
    vaxView,
    rmFormUnit,
  },
  data () {
    return {
      afterPost () {
        if ( this.success && store.getters.accessLevel === 3 ) { // unit principal
          window.location = "/logout";
        }
      }
    };
  },
  mixins: [
    submitPostMixin,
    jsonViewDataMixin
  ]
}
